version: '2'
services:
  backend:
    build: ./backend-container
    command: serve
    env_file:
     - env
    ports:
     - "5000:5000"
    volumes:
        - ~/opt/backend:/opt/backend/
    depends_on:
     - postgres
     - rabbitmq
  postgres:
    image: postgres:9.4
    ports:
     - "5432:5432"
  nginx:
    image: nginx:1.10.0
    depends_on:
     - backend
    ports:
     - "80:80"
    volumes:
     - ~/opt/frontend/:/opt/frontend
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
     - /etc/nginx/ssl/:/etc/nginx/ssl/
  rabbitmq:
    image: rabbitmq:3.6.5
    ports:
     - "5672:5672"
     - "15672:15672"
