# Install Packages
RUN \	
	apt-get install -y \
		curl \
		nginx \
		libpq-dev \
		python3-dev \
		python-virtualenv \
		rabbitmq-server \
		git-core \
		nodejs \
		nodejs-legacy \
		npm \
		build-essential \
		ca-certificates \
		wget

# Install Postgres9.4
RUN \
	echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" \
       > /etc/apt/sources.list.d/pgdg.list && \
  	curl -sL https://www.postgresql.org/media/keys/ACCC4CF8.asc \
       | apt-key add - && \
	apt-get update && \
	apt-get install -y \
		postgresql-${PG_VERSION} \
		postgresql-contrib-${PG_VERSION}

## Building Frontend and Backend
# Create contentools dir
#RUN cd ~/ && \
#	mkdir contentools && \

# Make ssh dir
RUN mkdir ${SSH_DIR}

# Create known_hosts
RUN touch /root/.ssh/known_hosts
# Add github to known hosts
RUN ssh-keyscan -T 30 github.com >> /root/.ssh/known_hosts

# Fetch backend repository into contentool dir
ADD docker-backend ${SSH_DIR}id_rsa
RUN chmod 600 ${SSH_DIR}id_rsa && \
	git clone git@github.com:contentools/backend.git ${BACKEND_FOLDER} && \
	cd ${BACKEND_FOLDER} && \
	git checkout dev

# Instal nodejs
RUN \
	apt-get install -y 

# Fetch and build frontend repository into contentool dir
ADD docker-frontend ${SSH_DIR}id_rsa
RUN \
	chmod 600 ${SSH_DIR}id_rsa && \
	git clone git@github.com:contentools/frontend.git ${FRONTEND_FOLDER} && \
	cd ${FRONTEND_FOLDER} && \
	git checkout dev 

# Build the frontend
RUN \
	cd ${FRONTEND_FOLDER} && \
	rm -rf node_modules/ && \
	rm -rf ~/.npm && \
	npm install -g bower && \
	npm install -g grunt-wiredep && \
	bower install --allow-root && \
	npm cache clean && \
	make build
	
############################################################
# Dockerfile that creates a container for running Contentools
# (which is just a modified version of Ubuntu)
#
# Recommended build command:
#
#   docker build -t davivc/contentools /path/to/Dockerfile/dir/.
#
# Recommended run command:
#
#   docker run -t --hostname="contentools.dev" --name=contentools. -p 8443:443 -p 8080:80 foreman
#
############################################################
FROM ubuntu:14.04
MAINTAINER Davi Candido <davivc@gmail.com>

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ENV PG_VERSION 9.4
ENV USER contentools_dev
ENV PASS 12345
ENV BACKEND_FOLDER /root/contentools/backend
ENV FRONTEND_FOLDER /root/contentools/frontend
ENV HOSTNAME contentools.dev
ENV SSH_DIR /root/.ssh/

# Let the conatiner know that there is no tty
ENV DEBIAN_FRONTEND noninteractive

# Keep upstart from complaining
RUN dpkg-divert --local --rename --add /sbin/initctl
RUN ln -sf /bin/true /sbin/initctl

# Avoid ERROR: invoke-rc.d: policy-rc.d denied execution of start.
RUN echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d
RUN apt-get upgrade -y

# Update and install some useful apts
RUN apt-get update
RUN \	
	apt-get install -y \
		curl \
		ca-certificates \
		wget

## Install Foreman
# Add the Foreman repos
RUN \
	wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb && \
	dpkg -i puppetlabs-release-trusty.deb

RUN \
	echo "deb http://deb.theforeman.org/ trusty 1.12" > /etc/apt/sources.list.d/foreman.list && \
	echo "deb http://deb.theforeman.org/ plugins 1.12" >> /etc/apt/sources.list.d/foreman.list && \
	wget -q https://deb.theforeman.org/pubkey.gpg -O- | apt-key add -

RUN \
	apt-get update && apt-get -y install foreman-installer


# Install Postgres9.4
#RUN \
#	echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" \
#       > /etc/apt/sources.list.d/pgdg.list && \
#  	curl -sL https://www.postgresql.org/media/keys/ACCC4CF8.asc \
#       | apt-key add - && \
#	apt-get update && \
#	apt-get install -y \
#		postgresql-${PG_VERSION} \
#		postgresql-contrib-${PG_VERSION} \
#		postgresql-client-${PG_VERSION} \
#		postgresql-server-dev-${PG_VERSION}



#RUN \ 
#	apt-get -y install wget && \
#	echo "deb http://deb.theforeman.org/ trusty 1.9" > /etc/apt/sources.list.d/foreman.list && \
#	echo "deb http://deb.theforeman.org/ plugins 1.9" >> /etc/apt/sources.list.d/foreman.list && \
#	wget -q http://deb.theforeman.org/pubkey.gpg -O- | apt-key add - && \
#	apt-get update && \
#	apt-get -y install facter foreman-installer

# Copy our first_run.sh script into the container:
# COPY first_run.sh /usr/local/bin/first_run.sh
# RUN chmod 755 /usr/local/bin/first_run.sh

# Also copy our foreman installer script
#COPY install_foreman.sh /opt/install_foreman.sh
#RUN chmod 755 /opt/install_foreman.sh

# Perform the installation
#RUN bash /opt/install_foreman.sh
#RUN rm -f /opt/install_foreman.sh # Don't need it anymore

#EXPOSE 80
#EXPOSE 443
#EXPOSE 5000
#EXPOSE 8443

# Our 'first run' script which takes care of resetting the DB the first time
# the image runs with subsequent runs being left alone:
# CMD ["/usr/local/bin/first_run.sh"]


# Create symlinks
RUN \
	cd ${BACKEND_FOLDER} && \
	ln -s ${FRONTEND_FOLDER} && \
	cd /opt && \
	ln -s ${BACKEND_FOLDER} contentools

# Contentools create database
COPY start_postgres.sh /root/start_postgres.sh
CMD ["/root/start_postgres.sh"]

# Nginx
RUN \
	rm -f /etc/nginx/nginx.conf && \
	ln -s ${BACKEND_FOLDER}/conf/nginx.dev.conf /etc/nginx/nginx.conf && \
	service nginx restart

# Virtual env e run platform
RUN \
	cd ${BACKEND_FOLDER} && \
	cp .env.example .env

RUN \
	virtualenv venv --python=python3

# Install foreman
RUN \
	wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb && \
	dpkg -i puppetlabs-release-trusty.deb

RUN \ 
	echo "deb http://deb.theforeman.org/ trusty 1.9" > /etc/apt/sources.list.d/foreman.list && \
	echo "deb http://deb.theforeman.org/ plugins 1.9" >> /etc/apt/sources.list.d/foreman.list && \
	wget -q http://deb.theforeman.org/pubkey.gpg -O- | apt-key add -

RUN \
	apt-get update && \
	apt-get -y install foreman-installer
	

RUN \
#	echo "contentools.dev" > /etc/hostname && \
# 	sed -i "2i127.0.1.1  contentools.dev contentools" /etc/hosts && \
#	foreman-installer

# Install requirements and run plataform
#RUN \
	#source venv/bin/activate && \
	#source .env && \
	#export DATABASE_URL=postgres://contentools_dev:12345@localhost:5432/contentools && \
	#pip install -r requirements.txt && \
	#python manage.py migrate_schemas --shared && \
	#yes | ./restore_schemas.sh contentools && \
	#nohup foreman start > /var/log/contentools_docker.log 2>&1 &

#EXPOSE 80
#EXPOSE 8080
#EXPOSE 5000

# is not recommended as it persists in the final image
# but this avoid TERM error during build
# ENV DEBIAN_FRONTEND noninteractive
