version: '2'
services:
  frontend:
    build: ./frontend-container
    command: watch
    env_file:
     - env
    ports:
     - "35729:35729"
    volumes:
        - ./code/frontend/:/opt/frontend/
  backend:
    build: ./backend-container
    command: serve
    env_file:
     - env
    ports:
     - "5000:5000"
    volumes:
        - ./code/backend/:/opt/backend/
    depends_on:
     - postgres
  postgres:
    image: postgres:9.4
    ports:
     - "5432:5432"
  nginx:
    image: nginx:1.10.0
    depends_on:
     - backend
     - frontend
    ports:
     - "80:80"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
     - /etc/nginx/ssl/:/etc/nginx/ssl/
  rabbitmq:
    image: rabbitmq:3.6.5
    ports:
     - "5672:5672"
     - "15672:15672"
