version: '2'
services:
  web:
    build: .
    env_file:
    - env
    ports:
     - "5000:5000"
    volumes:
        #     - ./code/:/root/contentools/
        - /opt/contentools/
    depends_on:
     - postgres
  postgres:
    image: postgres:9.4
    ports:
     - "5432:5432"
  nginx:
    image: nginx:1.10.0
    depends_on:
     - web
    ports:
     - "80:80"
    volumes:
     - /opt/frontend/:/opt/frontend
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
     - /etc/nginx/ssl/:/etc/nginx/ssl/
